cask_args appdir: '/Applications'

brew 'imagemagick'
brew 'postgresql@14'
brew 'redis'
brew 'ruby-build'
brew 'wget'
brew 'yt-dlp'

cask '1password'
cask 'plex'
cask 'steam'
cask 'warp'
cask 'whatsapp'
cask 'windsurf'
cask 'visual-studio-code'
cask 'vlc'
cask 'zed'
cask 'zoom'