cask_args appdir: '/Applications'

brew 'imagemagick'
brew 'minikube'
brew 'postgresql@14'
brew 'python'
brew 'redis'
brew 'ruby-build'
brew 'tree'
brew 'wget'
brew 'yt-dlp'

cask '1password'
cask '1password-cli'
cask 'basictex'
cask 'docker'
cask 'plex'
cask 'steam'
cask 'warp'
cask 'whatsapp'
cask 'windsurf'
cask 'vagrant'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'vlc'
cask 'zed'
cask 'zoom'
